"use client"

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"
import { reportsAdminApi } from "@/services/admin"
import { PageHeader, DataTable, FilterBar, SelectFilter, Pagination, Btn, Modal, StatusBadge } from "@/components/ui/admin"
import { Plus, FileText, Download, RefreshCw } from "lucide-react"
import { useState } from "react"

const REPORT_TYPES = [
  { value: "department_monthly", label: "Department Monthly" },
  { value: "attendance_summary", label: "Attendance Summary" },
  { value: "marks_analysis", label: "Marks Analysis" },
  { value: "at_risk_students", label: "At-Risk Students" },
  { value: "placement_summary", label: "Placement Summary" },
  { value: "fee_collection", label: "Fee Collection" },
  { value: "naac_criterion_1", label: "NAAC Criterion 1" },
  { value: "naac_criterion_2", label: "NAAC Criterion 2" },
  { value: "nirf", label: "NIRF Report" },
  { value: "annual_report", label: "Annual Report" },
  { value: "custom", label: "Custom" },
]

const STATUS_COLOR: Record<string, string> = {
  queued: "warning", generating: "warning", completed: "success", failed: "danger",
}

const FORMAT_ICONS: Record<string, string> = {
  pdf: "📄", docx: "📝", xlsx: "📊", pptx: "📑",
}

export default function ReportsPage() {
  const [page, setPage] = useState(1)
  const [typeFilter, setTypeFilter] = useState("")
  const [statusFilter, setStatusFilter] = useState("")
  const [modalOpen, setModalOpen] = useState(false)
  const [genForm, setGenForm] = useState({ title: "", report_type: "attendance_summary", format: "pdf" })

  const qc = useQueryClient()

  const { data: result, isLoading } = useQuery({
    queryKey: ["admin-reports", page, typeFilter, statusFilter],
    queryFn: () => reportsAdminApi.list({
      page, page_size: 20,
      report_type: typeFilter || undefined,
      status: statusFilter || undefined,
    }),
    staleTime: 20_000,
  })

  const generateMut = useMutation({
    mutationFn: (data: any) => reportsAdminApi.create(data),
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ["admin-reports"] })
      setModalOpen(false)
    },
  })

  const reports = result?.data || []
  const total = result?.total || 0

  const columns = [
    {
      key: "title", label: "Report",
      render: (r: any) => (
        <div>
          <div className="font-semibold text-sm text-[#0F172A]">{r.title}</div>
          <div className="text-xs text-[#94A3B8]">{r.report_type.replace(/_/g, " ")}</div>
        </div>
      ),
    },
    {
      key: "format", label: "Format",
      render: (r: any) => (
        <span className="font-mono text-xs font-bold">{FORMAT_ICONS[r.format] || ""} {r.format.toUpperCase()}</span>
      ),
    },
    { key: "status", label: "Status", render: (r: any) => <StatusBadge status={STATUS_COLOR[r.status]} label={r.status} /> },
    { key: "generated_by_name", label: "Generated By" },
    {
      key: "file_size_kb", label: "Size",
      render: (r: any) => r.file_size_kb ? <span className="font-mono text-xs">{r.file_size_kb} KB</span> : <span className="text-[#94A3B8]">—</span>,
    },
    {
      key: "created_at", label: "Created",
      render: (r: any) => (
        <span className="text-xs text-[#94A3B8]">{new Date(r.created_at).toLocaleDateString("en-IN", { dateStyle: "medium" })}</span>
      ),
    },
    {
      key: "actions", label: "",
      render: (r: any) => r.status === "completed" && r.file_path && (
        <button className="text-xs px-2 py-1 rounded-lg text-[#6366F1] hover:bg-[#EEF2FF] transition flex items-center gap-1">
          <Download size={11} /> Download
        </button>
      ),
    },
  ]

  return (
    <div>
      <PageHeader
        title="Reports"
        subtitle="Generate and manage compliance and analytics reports"
        badge={`${total} reports`}
        actions={
          <div className="flex gap-2">
            <Btn variant="secondary" icon={RefreshCw} onClick={() => qc.invalidateQueries({ queryKey: ["admin-reports"] })}>Refresh</Btn>
            <Btn variant="primary" icon={Plus} onClick={() => setModalOpen(true)}>Generate Report</Btn>
          </div>
        }
      />

      <FilterBar
        filters={
          <>
            <SelectFilter value={typeFilter} onChange={(v) => { setTypeFilter(v); setPage(1) }} options={REPORT_TYPES} placeholder="All Types" />
            <SelectFilter value={statusFilter} onChange={(v) => { setStatusFilter(v); setPage(1) }}
              options={[
                { value: "queued", label: "Queued" },
                { value: "generating", label: "Generating" },
                { value: "completed", label: "Completed" },
                { value: "failed", label: "Failed" },
              ]} placeholder="All Statuses" />
          </>
        }
      />

      <DataTable columns={columns} data={reports} loading={isLoading} rowKey={(r) => r.id} emptyMessage="No reports generated yet. Click 'Generate Report' to create one." />
      <Pagination page={page} pageSize={20} total={total} onChange={setPage} />

      {/* Generate Report Modal */}
      <Modal open={modalOpen} title="Generate New Report" onClose={() => setModalOpen(false)}>
        <form onSubmit={(e: any) => {
          e.preventDefault()
          generateMut.mutate(genForm)
        }} className="flex flex-col gap-4">
          <div className="flex flex-col gap-1">
            <label className="text-xs font-semibold text-[#374151]">Report Title *</label>
            <input required value={genForm.title} onChange={e => setGenForm(f => ({ ...f, title: e.target.value }))}
              placeholder="e.g. Attendance Summary - Nov 2024"
              className="text-sm px-3 py-2 border border-[#E2E8F0] rounded-xl outline-none focus:ring-2 focus:ring-[#6366F1]/30" />
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs font-semibold text-[#374151]">Report Type *</label>
            <select value={genForm.report_type} onChange={e => setGenForm(f => ({ ...f, report_type: e.target.value }))}
              className="text-sm px-3 py-2 border border-[#E2E8F0] rounded-xl outline-none focus:ring-2 focus:ring-[#6366F1]/30">
              {REPORT_TYPES.map(t => <option key={t.value} value={t.value}>{t.label}</option>)}
            </select>
          </div>
          <div className="flex flex-col gap-1">
            <label className="text-xs font-semibold text-[#374151]">Format</label>
            <div className="flex gap-2">
              {["pdf", "xlsx", "docx"].map(fmt => (
                <button key={fmt} type="button"
                  onClick={() => setGenForm(f => ({ ...f, format: fmt }))}
                  className={`flex-1 py-2 rounded-xl border text-sm font-semibold transition ${genForm.format === fmt ? "border-[#6366F1] bg-[#EEF2FF] text-[#6366F1]" : "border-[#E2E8F0] text-[#64748B]"}`}
                >
                  {FORMAT_ICONS[fmt]} {fmt.toUpperCase()}
                </button>
              ))}
            </div>
          </div>
          <div className="flex gap-3 pt-1">
            <Btn variant="secondary" onClick={() => setModalOpen(false)} type="button" className="flex-1">Cancel</Btn>
            <Btn variant="primary" type="submit" isLoading={generateMut.isPending} icon={FileText} className="flex-1">Queue Report</Btn>
          </div>
        </form>
      </Modal>
    </div>
  )
}
